overrides:
  'vue': '3.6.0-beta.6'
  '@vue/compiler-core': '3.6.0-beta.6'
  '@vue/compiler-dom': '3.6.0-beta.6'
  '@vue/compiler-sfc': '3.6.0-beta.6'
  '@vue/compiler-ssr': '3.6.0-beta.6'
  '@vue/compiler-vapor': '3.6.0-beta.6'
  '@vue/reactivity': '3.6.0-beta.6'
  '@vue/runtime-core': '3.6.0-beta.6'
  '@vue/runtime-dom': '3.6.0-beta.6'
  '@vue/runtime-vapor': '3.6.0-beta.6'
  '@vue/server-renderer': '3.6.0-beta.6'
  '@vue/shared': '3.6.0-beta.6'
  '@vue/compat': '3.6.0-beta.6'

peerDependencyRules:
  allowAny:
    - 'vue'
