import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const ROOT = process.cwd();
const SOURCE_URL = "https://agents.craft.do/mermaid";
const OUTPUT_PATH = path.join(ROOT, "src/data/officialSamples.ts");

function toPrettyJson(value) {
  return JSON.stringify(value, null, 2);
}

async function writeIfChanged(filePath, content) {
  let previous = null;
  try {
    previous = await readFile(filePath, "utf8");
  } catch {
    previous = null;
  }

  if (previous === content) {
    return false;
  }

  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, content, "utf8");
  return true;
}

function extractSamplesArrayLiteral(html) {
  const marker = "var samples = ";
  const markerIndex = html.indexOf(marker);
  if (markerIndex < 0) {
    throw new Error("Cannot find `var samples =` in official site payload.");
  }

  const startIndex = html.indexOf("[", markerIndex + marker.length);
  if (startIndex < 0) {
    throw new Error("Cannot locate samples array start.");
  }

  let depth = 0;
  let inString = false;
  let escaped = false;

  for (let index = startIndex; index < html.length; index += 1) {
    const char = html[index];

    if (inString) {
      if (escaped) {
        escaped = false;
        continue;
      }

      if (char === "\\") {
        escaped = true;
        continue;
      }

      if (char === '"') {
        inString = false;
      }
      continue;
    }

    if (char === '"') {
      inString = true;
      continue;
    }

    if (char === "[") {
      depth += 1;
      continue;
    }

    if (char === "]") {
      depth -= 1;
      if (depth === 0) {
        return html.slice(startIndex, index + 1);
      }
    }
  }

  throw new Error("Cannot locate samples array end.");
}

function isPlainObject(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function normalizeCategory(category) {
  if (category === "Hero") {
    return "Basic";
  }

  return category;
}

function normalizeTitle(title, category) {
  if (category === "Basic") {
    return "Basic";
  }

  return title;
}

function normalizeSource(source) {
  return source.replace(/\r\n?/gu, "\n");
}

function toOfficialSamples(samplesPayload) {
  if (!Array.isArray(samplesPayload)) {
    throw new Error("Invalid samples payload: expected an array.");
  }

  return samplesPayload.map((item, index) => {
    if (!isPlainObject(item)) {
      throw new Error(`Invalid sample at index ${index}: expected an object.`);
    }

    const titleRaw = typeof item.title === "string" ? item.title : "";
    const descriptionRaw = typeof item.description === "string" ? item.description : "";
    const sourceRaw = typeof item.source === "string" ? item.source : "";
    const categoryRaw = typeof item.category === "string" ? item.category : "Other";

    const category = normalizeCategory(categoryRaw);
    const options = isPlainObject(item.options) ? item.options : {};

    return {
      id: index,
      title: normalizeTitle(titleRaw, category),
      description: descriptionRaw,
      source: normalizeSource(sourceRaw),
      category,
      options,
    };
  });
}

function getCategoryList(samples) {
  const categories = [];
  const seen = new Set();

  for (const sample of samples) {
    if (seen.has(sample.category)) {
      continue;
    }

    seen.add(sample.category);
    categories.push(sample.category);
  }

  if (!seen.has("Basic")) {
    categories.unshift("Basic");
  }

  return categories;
}

function renderOfficialSamplesFile(samples) {
  const categories = getCategoryList(samples);

  return `// Generated by scripts/sync-official-samples.ts. Do not edit manually.
export interface OfficialSample {
  id: number;
  title: string;
  description: string;
  source: string;
  category: string;
  options: Record<string, unknown>;
}

function trimSourceTrailingSpaces(source: string): string {
  return source
    .split("\\n")
    .map((line) => line.replace(/[ \\t]+$/u, ""))
    .join("\\n");
}

function normalizeSourceIndentation(source: string): string {
  return source
    .split("\\n")
    .map((line) => {
      const leadingWhitespaceMatch = line.match(/^[ \\t]+/u);
      if (!leadingWhitespaceMatch) {
        return line;
      }

      const normalizedLeadingWhitespace = leadingWhitespaceMatch[0]
        .replace(/\\t/gu, "  ")
        .replace(/ {4}/gu, "  ");
      return \`\${normalizedLeadingWhitespace}\${line.slice(leadingWhitespaceMatch[0].length)}\`;
    })
    .join("\\n");
}

export const OFFICIAL_SAMPLE_CATEGORIES: string[] = ${toPrettyJson(categories)};

const RAW_OFFICIAL_SAMPLES: OfficialSample[] = ${toPrettyJson(samples)};

export const OFFICIAL_SAMPLES: OfficialSample[] = RAW_OFFICIAL_SAMPLES.map((sample) => ({
  ...sample,
  source: normalizeSourceIndentation(trimSourceTrailingSpaces(sample.source)),
}));
`;
}

async function main() {
  const response = await fetch(SOURCE_URL, {
    headers: {
      "user-agent": "beautiful-mermaid-playground-sync-script",
    },
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch official site: ${response.status} ${response.statusText}`);
  }

  const html = await response.text();
  const arrayLiteral = extractSamplesArrayLiteral(html);
  const samplesPayload = JSON.parse(arrayLiteral);
  const samples = toOfficialSamples(samplesPayload);
  const output = renderOfficialSamplesFile(samples);

  const written = await writeIfChanged(OUTPUT_PATH, output);
  const verb = written ? "Updated" : "Up-to-date";
  console.log(`${verb} ${path.relative(ROOT, OUTPUT_PATH)} (${samples.length} samples)`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
